beyond-sw-camp/be03-fin-4team-HarboR

- .idea/uiDesigner.xml
- Harbor_salary/src/main/java/com/example/harbor_salary/entity/Salary.java
<br />
- Salary 클래스명 및 엔티티 변수명 수정
<br />
1. Salary 클래스명 및 엔티티 변수명 수정
<br />
> [UPDATE] Salary 클래스명 및 엔티티 변수명 수정

- .idea/dataSources.xml
- Harbor_Login/src/main/java/com/example/harbor_login/Login/controller/AdminController.java
- Harbor_Login/src/main/java/com/example/harbor_login/Login/controller/LoginController.java
- Harbor_Login/src/main/java/com/example/harbor_login/Login/domain/Login.java
- Harbor_Login/src/main/java/com/example/harbor_login/Login/dto/LoginMemberResDto.java
- Harbor_Login/src/main/java/com/example/harbor_login/Login/repository/LoginRepository.java
- Harbor_Login/src/main/java/com/example/harbor_login/Login/service/LoginService.java
- [o] 기능 추가
<br />
<br />
<br />
<br />
> 240327 list, delete Add

- Harbor_Login/src/main/java/com/example/harbor_login/Login/controller/LoginController.java
- Harbor_Login/src/main/java/com/example/harbor_login/Login/dto/LoginMemberResponseDto.java
- Harbor_Login/src/main/java/com/example/harbor_login/Login/service/LoginService.java
- Harbor_Login/src/main/java/com/example/harbor_login/global/config/JwtTokenProvider.java
<br />
myinfo 추가
<br />
feignclient 연습을 위해 myinfo 추가
<br />
없읍.
<br />
> 240328 myinfo add

- Harbor_salary/src/main/java/com/example/harbor_salary/controller/SalaryController.java
- Harbor_salary/src/main/java/com/example/harbor_salary/domain/Salary.java
- Harbor_salary/src/main/java/com/example/harbor_salary/service/SalaryService.java
- [x ] 버그 수정
<br />
- 급여 목록 조회 복구 및 엔티티 변수 수정
> [Bug] 급여 목록 조회 복구 및 엔티티 변수 수정

- Harbor_Login/src/main/java/com/example/harbor_login/Login/controller/LoginController.java
- Harbor_Login/src/main/java/com/example/harbor_login/global/config/CustomUserDetails.java
- Harbor_Login/src/main/java/com/example/harbor_login/global/config/JwtTokenProvider.java
- Harbor_Login/src/main/java/com/example/harbor_login/global/filter/JwtAuthFilter.java
> 240328 login token empyloeeId ADD

- Harbor_Login/src/main/java/com/example/harbor_login/Login/controller/AdminController.java
- Harbor_Login/src/main/java/com/example/harbor_login/Login/controller/LoginController.java
- Harbor_Login/src/main/java/com/example/harbor_login/Login/service/EmailService.java
- Harbor_Login/src/main/java/com/example/harbor_login/Login/service/LoginService.java
- Harbor_Login/src/main/java/com/example/harbor_login/client/LoginToEmployeeClient.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/controller/EmployeeController.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/dto/response/GetEmployResponse.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/repository/EmployeeRepository.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/service/EmployeeService.java
- Harbor_salary/src/main/java/com/example/harbor_salary/client/GetEmployResponse.java
- Harbor_salary/src/main/java/com/example/harbor_salary/client/SalaryClient.java
- Harbor_salary/src/main/java/com/example/harbor_salary/client/SalaryEmployeeClient.java
- Harbor_salary/src/main/java/com/example/harbor_salary/controller/SalaryController.java
- Harbor_salary/src/main/java/com/example/harbor_salary/dto/response/MySalaryDetailResponse.java
- Harbor_salary/src/main/java/com/example/harbor_salary/repository/SalaryRepository.java
- Harbor_salary/src/main/java/com/example/harbor_salary/service/SalaryService.java
<br />
- 급여 생성 api ( 어드민 권한)
- 사원 별 급여목록조회
- 사원 급여 상세 조회
- 변수 명 오타 수정
<br />
- 오타 수정 때문에 코드가 꼬일 수 있습니다. 유의 해주세요
> [ADD] 급여 직원 별 생성 및  급여 목록조회

- .idea/compiler.xml
- Harbor_Login/src/main/resources/application.yml
- Harbor_employee/build.gradle
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/domain/Department.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/domain/Employee.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/dto/response/ExcelDataDto.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/repository/DepartmentRepository.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/repository/EmployeeRepository.java
- Harbor_employee/src/main/java/com/example/harbor_employee/HarborEmployeeApplication.java
- Harbor_employee/src/main/java/com/example/harbor_employee/PersonnelAppointment/controller/PersonnelAppointmentController.java
- Harbor_employee/src/main/java/com/example/harbor_employee/PersonnelAppointment/domain/PersonnelAppointment.java
- Harbor_employee/src/main/java/com/example/harbor_employee/PersonnelAppointment/repository/PersonnelAppointmentRepository.java
- Harbor_employee/src/main/java/com/example/harbor_employee/PersonnelAppointment/service/PersonnelAppointmentService.java
- Harbor_employee/src/main/java/com/example/harbor_employee/global/config/RedisConfig.java
- Harbor_employee/src/main/java/com/example/harbor_employee/global/error/ExceptionHandlerAdvice.java
- Harbor_employee/src/main/java/com/example/harbor_employee/global/util/EmployeeScheduler.java
- Harbor_employee/src/main/java/com/example/harbor_employee/global/util/RedisUtil.java
- Harbor_employee/src/main/resources/application.yml
<br />
redis , scheduler 추가
<br />
해당 날짜에 오면 인사이동 
레디스의 키값을 고민하다가 날짜로 집어넣음
<br />
> 240402 redis, scheduler add 

- Harbor_Login/src/main/java/com/example/harbor_login/global/config/CustomUserDetails.java
- Harbor_Login/src/main/java/com/example/harbor_login/global/filter/JwtAuthFilter.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/domain/Employee.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/domain/EmployeeCode.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/dto/response/GetEmployResponse.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/service/EmployeeService.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Eworks/controller/EworksController.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Eworks/domain/Eworks.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Eworks/dto/EworksCreateReqDto.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Eworks/repository/EworksRepository.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Eworks/service/EworksService.java
- Harbor_employee/src/main/java/com/example/harbor_employee/PersonnelAppointment/service/PersonnelAppointmentService.java
- Harbor_employee/src/main/java/com/example/harbor_employee/global/config/CustomUserDetails.java
- Harbor_employee/src/main/java/com/example/harbor_employee/global/filter/JwtAuthFilter.java
- Harbor_salary/src/main/java/com/example/harbor_salary/client/GetEmployResponse.java
- Harbor_salary/src/main/java/com/example/harbor_salary/config/CustomUserDetails.java
- Harbor_salary/src/main/java/com/example/harbor_salary/filter/JwtAuthFilter.java
> [HOTFIX] 병합 코드 에러 처리

- Harbor_Login/src/main/java/com/example/harbor_login/Login/controller/LoginController.java
- Harbor_Login/src/main/java/com/example/harbor_login/Login/dto/EmailLoginReqDto.java
- Harbor_Login/src/main/java/com/example/harbor_login/Login/dto/EmployeeLoginReqDto.java
- Harbor_Login/src/main/java/com/example/harbor_login/Login/service/LoginService.java
<br />
- 이메일로그인 ,employee 로그인 분리
<br />
빈 칸이면 bindingExcepiton
<br />
<br />
없음
> [UPDATE] 이메일로그인, 사원번호 로그인으로 수정

- Harbor_Login/src/main/java/com/example/harbor_login/Login/controller/LoginController.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/controller/EmployeeController.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/domain/Employee.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/dto/request/EmployeeUpdateRequestDto.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/dto/response/EmployeeDetailResDto.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/service/EmployeeService.java
<br />
회원 수정
<br />
회원 수정
<br />
<br />
> [ADD] 회원 수정 

- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/controller/EmployeeController.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/domain/Employee.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/dto/response/ExcelEmployeeDto.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/service/EmployeeService.java
<br />
인사정보 엑셀로 기본데이터 생성
<br />
엑셀파일로만 가능
<br />
<br />
> [ADD] 엑셀파일로 기본 정보 등록

- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/controller/EmployeeController.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/domain/Employee.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/dto/response/ExcelEmployeeDto.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/service/EmployeeService.java
- Harbor_employee/src/main/java/com/example/harbor_employee/kafka/KafkaTestDto.java
- Harbor_employee/src/main/java/com/example/harbor_employee/kafka/TestConsumer.java
- Harbor_total/src/main/java/com/example/harbor_total/global/kafka/KafkaConsumerConfig.java
- Harbor_total/src/main/java/com/example/harbor_total/global/kafka/KafkaListenerList.java
> [ADD] Employee -> Total 회원 생성 kafka 사용

- .gitignore
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/controller/EmployeeController.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/service/EmployeeService.java
- Harbor_total/build.gradle
- Harbor_total/src/main/java/com/example/harbor_total/HarborTotalApplication.java
- Harbor_total/src/main/java/com/example/harbor_total/global/common/CommonResponse.java
- Harbor_total/src/main/java/com/example/harbor_total/global/common/InitialDataLoader.java
- Harbor_total/src/main/java/com/example/harbor_total/global/config/CustomUserDetails.java
- Harbor_total/src/main/java/com/example/harbor_total/global/config/JwtTokenProvider.java
- Harbor_total/src/main/java/com/example/harbor_total/global/config/SecurityConfig.java
- Harbor_total/src/main/java/com/example/harbor_total/global/error/ErrorResponseDto.java
- Harbor_total/src/main/java/com/example/harbor_total/global/error/ExceptionHandlerAdvice.java
- Harbor_total/src/main/java/com/example/harbor_total/global/error/handlerExpetion.java
- Harbor_total/src/main/java/com/example/harbor_total/global/filter/JwtAuthFilter.java
- Harbor_total/src/main/java/com/example/harbor_total/global/support/Role.java
- docker-compose.yml
> [SET] total setting

- .idea/dataSources.xml
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/domain/Employee.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/dto/request/EmployeeUpdateRequestDto.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/service/EmployeeService.java
- Harbor_total/src/main/java/com/example/harbor_total/Annual/domain/Annual.java
- Harbor_total/src/main/java/com/example/harbor_total/Attendance/dto/request/AttendanceFlexibleWorkReqDto.java
- Harbor_total/src/main/java/com/example/harbor_total/Attendance/dto/response/AttendanceListResDto.java
- Harbor_total/src/main/java/com/example/harbor_total/Attendance/service/AttendanceService.java
- Harbor_total/src/main/java/com/example/harbor_total/Employee/domain/Employee.java
- Harbor_total/src/main/resources/application.yml
> [UPDATE] Emplyoee 수정 + 정민코드와 합치기

- Harbor_Login/src/main/java/com/example/harbor_login/global/config/WebConfig.java
- Harbor_total/src/main/java/com/example/harbor_total/Annual/repository/AnnualRepository.java
- Harbor_total/src/main/java/com/example/harbor_total/Attendance/repository/AttendanceRepository.java
- Harbor_total/src/main/java/com/example/harbor_total/Attendance/service/AttendanceService.java
<br />
<br />
휴가 체크 
<br />
<br />
휴가 신청 해줘야함
> [ADD] 휴가 있는지 확인

- Harbor_total/src/main/java/com/example/harbor_total/Annual/controller/AnnualController.java
- Harbor_total/src/main/java/com/example/harbor_total/Annual/domain/Annual.java
- Harbor_total/src/main/java/com/example/harbor_total/Annual/service/AnnualService.java
- Harbor_total/src/main/java/com/example/harbor_total/Attendance/domain/Attendance.java
- Harbor_total/src/main/java/com/example/harbor_total/Attendance/dto/request/AttendanceFlexibleWorkReqDto.java
- Harbor_total/src/main/java/com/example/harbor_total/Attendance/dto/response/AttendanceListResDto.java
- Harbor_total/src/main/java/com/example/harbor_total/Attendance/service/AttendanceService.java
- Harbor_total/src/main/java/com/example/harbor_total/Employee/domain/Employee.java
<br />
- 휴가 연차 신청하기
<br />
1. 휴가, 반차 신청시 근무 확인
2. 1:1 단방향 관계에서 양방향 관계로 변경 (jpa에서 맺어주지 않음)
<br />
양방향 관계에서 
attendance 만들고 annual 만들고 attendance 업데이트 해주고 annual 업데이트 해주는 로직이 좀 어려웠음
<br />
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다
> [ADD] 휴가 연차  반차 신청

- Harbor_total/src/main/java/com/example/harbor_total/Annual/controller/AnnualController.java
- Harbor_total/src/main/java/com/example/harbor_total/Annual/domain/Annual.java
- Harbor_total/src/main/java/com/example/harbor_total/Annual/repository/AnnualRepository.java
- Harbor_total/src/main/java/com/example/harbor_total/Annual/service/AnnualService.java
- Harbor_total/src/main/java/com/example/harbor_total/Attendance/domain/Attendance.java
- Harbor_total/src/main/java/com/example/harbor_total/Attendance/repository/AttendanceRepository.java
- Harbor_total/src/main/java/com/example/harbor_total/Attendance/service/AttendanceService.java
> [ADD] 전자 결재 삭제 API

- Harbor_Login/src/main/java/com/example/harbor_login/global/config/WebConfig.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Employee/controller/EmployeeController.java
- Harbor_employee/src/main/java/com/example/harbor_employee/global/config/WebConfig.java
- Harbor_frontend/package-lock.json
- Harbor_frontend/package.json
- Harbor_frontend/src/main.ts
- Harbor_frontend/src/router/MainRoutes.ts
- Harbor_frontend/src/stores/apps/UserCard.ts
- Harbor_frontend/src/stores/auth.ts
- Harbor_frontend/src/utils/axios.ts
- Harbor_frontend/src/views/apps/test/TestQalendar.vue
- Harbor_frontend/src/views/apps/users/list/ListPage1.vue
- Harbor_gateway/src/main/java/com/example/harbor/GatewayApplication.java
- Harbor_gateway/src/main/java/com/example/harbor/securities/JwtGlobalFilter.java
- Harbor_gateway/src/main/resources/application.yml
- Harbor_total/src/main/java/com/example/harbor_total/Annual/domain/Annual.java
- Harbor_total/src/main/java/com/example/harbor_total/Annual/service/AnnualService.java
- Harbor_total/src/main/java/com/example/harbor_total/Attendance/service/AttendanceService.java
> [FIX] 여러 가지 수정사항들

- Harbor_frontend/src/stores/codetrans.ts
- Harbor_frontend/src/types/calendar/Events.ts
- Harbor_frontend/src/views/apps/test/TestQalendar.vue
- Harbor_frontend/src/views/apps/users/list/ListPage1.vue
- Harbor_total/src/main/java/com/example/harbor_total/Annual/service/AnnualService.java
- Harbor_total/src/main/java/com/example/harbor_total/Attendance/repository/AttendanceRepository.java
- Harbor_total/src/main/java/com/example/harbor_total/Attendance/service/AttendanceService.java
> [HOTFIX] 전자 결재 오류 수정

- Harbor_frontend/src/stores/codetrans.ts
- Harbor_frontend/src/views/dashboards/default/components/TotalGrowth.vue
- Harbor_frontend/src/views/dashboards/default/components/TotalIncome.vue
- Harbor_total/src/main/java/com/example/harbor_total/commute/dto/res/CommuteListResDto.java
<br />
월간 내 근무리스트가 나옵니다.
정상근무와 비정상 근무
<br />
처음에 들어오면 접속한 해당 월에 데이터들이 나오고
달력을 통해 고를수 있습니다.
휴가시 휴가 사이에 있는 출퇴근 시간은 찍히지 않습니다.
> [ADD] 월간 내 근무리스트

- Harbor_Login/src/main/java/com/example/harbor_login/Notice/controller/NoticeController.java
- Harbor_Login/src/main/java/com/example/harbor_login/Notice/dto/request/NoticeCreateReqDto.java
- Harbor_Login/src/main/java/com/example/harbor_login/Notice/dto/response/NoticeDetailRes.java
- Harbor_Login/src/main/java/com/example/harbor_login/Notice/dto/response/NoticeListRes.java
- Harbor_Login/src/main/java/com/example/harbor_login/Notice/service/NoticeService.java
- Harbor_Login/src/main/resources/application.yml
- Harbor_frontend/src/layouts/full/vertical-sidebar/sidebarItem.ts
- Harbor_frontend/src/router/MainRoutes.ts
- Harbor_frontend/src/stores/apps/UserCard.ts
- Harbor_frontend/src/stores/apps/mail.ts
- Harbor_frontend/src/views/apps/users/list/EmployeeListPage.vue
- Harbor_frontend/src/views/apps/users/list/SalaryCreate.vue
- Harbor_frontend/src/views/apps/users/list/noticeCreate.vue
- Harbor_frontend/src/views/apps/users/list/noticeList.vue
- Harbor_frontend/src/views/apps/users/list/noticedetail.vue
- Harbor_frontend/src/views/apps/users/list/severancePay.vue
- Harbor_frontend/src/views/apps/users/list/test.vue
- Harbor_frontend/src/views/dashboards/default/components/TotalEarning.vue
- Harbor_gateway/src/main/java/com/example/harbor/securities/JwtGlobalFilter.java
- Harbor_salary/src/main/java/com/example/harbor_salary/salary/service/SalaryService.java
> [ADD] 공지사항 / 퇴직금 페이지

- .idea/compiler.xml
- Harbor_Login/src/main/java/com/example/harbor_login/Notice/domain/Notice.java
- Harbor_Login/src/main/java/com/example/harbor_login/Notice/dto/request/NoticeUpdateReq.java
- Harbor_Login/src/main/java/com/example/harbor_login/Notice/service/NoticeService.java
- Harbor_frontend/src/router/MainRoutes.ts
- Harbor_frontend/src/stores/apps/NoticeCard.ts
- Harbor_frontend/src/utils/axios.ts
- Harbor_frontend/src/views/apps/mail/MailPage.vue
- Harbor_frontend/src/views/apps/users/list/noticeCreate.vue
- Harbor_frontend/src/views/apps/users/list/noticeList.vue
- Harbor_frontend/src/views/apps/users/list/noticedetail.vue
- Harbor_frontend/src/views/apps/users/list/noticeupdate.vue
- Harbor_frontend/src/views/apps/users/list/severancePay.vue
> [ADD] noticeupdate

- Harbor_Login/src/main/java/com/example/harbor_login/Login/service/LoginService.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Stock/JsoupComponent.java
- Harbor_employee/src/main/java/com/example/harbor_employee/Stock/StockDomain.java
- Harbor_frontend/src/views/dashboards/default/components/TotalIncome.vue
>  사원번호 없는사람 로그인안됨

- Harbor_frontend/src/stores/apps/UserCard.ts
- Harbor_frontend/src/views/apps/users/account-profile/profile1/ProfileTab.vue
- Harbor_frontend/src/views/apps/users/list/AttendanceListReq.vue
- Harbor_frontend/src/views/apps/users/list/AttendanceListRes.vue
- Harbor_frontend/src/views/apps/users/list/EmployeeListPage.vue
<br />
- Fix 사원 목록 조회 버그 수정
<br />
> [FIX] 사원 목록 조회 버그 수정
